namespace: opensearch-system

resources:
- ns.yaml
- helm-opensearch-master.yaml
- helm-opensearch-worker.yaml
- helm-opensearch-dashboard.yaml

patches : []

secretGenerator: 
  - name: usdf-opensearch-hostcert
    files:
    - opensearch/etc/.secrets/hostcert.pem

  - name: usdf-opensearch-hostkey
    files:
    - opensearch/etc/.secrets/hostkey.pem

  - name: usdf-opensearch-admin-pw
    files:
    - opensearch/etc/.secrets/admin-pw
    literals:
    - username=admin

  - name: usdf-opensearch-tls
    files:
    - cert=opensearch/etc/.secrets/hostcert.pem
    - key=opensearch/etc/.secrets/hostkey.pem
